# Generated by Django 2.2 on 2019-04-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_sluf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sluf',
            new_name='slug',
        ),
    ]
